# Generated by Django 4.1.7 on 2023-02-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindmap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
