# Generated by Django 4.1.7 on 2023-02-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindmap', '0002_question_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsAddNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isadd', models.BooleanField()),
            ],
        ),
    ]
