# Generated by Django 4.1.7 on 2023-02-17 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindmap', '0004_node_delete_isaddnode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node1', models.IntegerField()),
                ('node2', models.IntegerField()),
            ],
        ),
    ]
