# Generated by Django 4.1.7 on 2023-02-18 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mindmap', '0005_relation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
