# Generated by Django 4.1.7 on 2023-02-18 02:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mindmap', '0006_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='type',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
